// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7vjn0JF5HV55M6HGGQBnd7i-YGG3rm5I',
    appId: '1:30344483724:web:6c70a75dc406eb0559bca9',
    messagingSenderId: '30344483724',
    projectId: 'helmet-companion',
    authDomain: 'helmet-companion.firebaseapp.com',
    databaseURL: 'https://helmet-companion-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'helmet-companion.firebasestorage.app',
    measurementId: 'G-YW5VZTK11E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOGDCv9BT9fBDFvZMKOC1TkI7Tv6hGwas',
    appId: '1:30344483724:android:cc0ebf7d797148ac59bca9',
    messagingSenderId: '30344483724',
    projectId: 'helmet-companion',
    databaseURL: 'https://helmet-companion-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'helmet-companion.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQUgr_CNlV5Ozg0QcDHKCWHU-dF-N0tL8',
    appId: '1:30344483724:ios:af6396df228b0bdb59bca9',
    messagingSenderId: '30344483724',
    projectId: 'helmet-companion',
    databaseURL: 'https://helmet-companion-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'helmet-companion.firebasestorage.app',
    iosBundleId: 'com.satra.helmet.companionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQUgr_CNlV5Ozg0QcDHKCWHU-dF-N0tL8',
    appId: '1:30344483724:ios:af6396df228b0bdb59bca9',
    messagingSenderId: '30344483724',
    projectId: 'helmet-companion',
    databaseURL: 'https://helmet-companion-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'helmet-companion.firebasestorage.app',
    iosBundleId: 'com.satra.helmet.companionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7vjn0JF5HV55M6HGGQBnd7i-YGG3rm5I',
    appId: '1:30344483724:web:9174abf3f825d8ab59bca9',
    messagingSenderId: '30344483724',
    projectId: 'helmet-companion',
    authDomain: 'helmet-companion.firebaseapp.com',
    databaseURL: 'https://helmet-companion-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'helmet-companion.firebasestorage.app',
    measurementId: 'G-7FC39Q6NPW',
  );
}
